// SPDX-FileCopyrightText: 2025 Dreykor <160512778+Dreykor@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 GabyChangelog <agentepanela2@gmail.com>
// SPDX-FileCopyrightText: 2025 Kyoth25f <kyoth25f@gmail.com>
// SPDX-FileCopyrightText: 2025 Tyranex <bobthezombie4@gmail.com>
// SPDX-FileCopyrightText: 2025 funkystationbot <funky@funkystation.org>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.Speech;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.IntrinsicVoiceModulator;

[GenerateTypedNameReferences]
public sealed partial class IntrinsicVoiceModulatorWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly SpriteSystem _spriteSystem;

    public event Action<string>? OnNameChanged;
    public event Action<ProtoId<JobIconPrototype>>? OnJobIconChanged;
    public event Action<ProtoId<SpeechVerbPrototype>?>? OnVerbChange;

    private const int JobIconColumnCount = 10;

    private List<ProtoId<JobIconPrototype>> _jobIcons = new();
    private ProtoId<JobIconPrototype>? _currentJobIconId = new();
    private Dictionary<ProtoId<JobIconPrototype>, Button> _jobIconButtons = new();
    private ButtonGroup? _jobIconButtonGroup = new();

    private List<(string, string)> _verbs = new();
    private string? _verb;

    public IntrinsicVoiceModulatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        NameLineEdit.OnTextEntered += e => OnNameChanged?.Invoke(e.Text);
        NameLineEdit.OnFocusExit += e => OnNameChanged?.Invoke(e.Text);

        SpeechVerbSelector.OnItemSelected += args =>
        {
            OnVerbChange?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
            SpeechVerbSelector.SelectId(args.Id);
        };
    }

    public void ReloadJobIcons()
    {
        var icons = _protoManager.EnumeratePrototypes<JobIconPrototype>()
            .Where(icon => icon.AllowSelection)
            .ToList();

        icons.Sort((x, y) => string.Compare(x.LocalizedJobName, y.LocalizedJobName, StringComparison.CurrentCulture));

        _jobIcons = icons.Select(icon => (ProtoId<JobIconPrototype>) icon.ID).ToList();
    }

    public void AddJobIcons()
    {
        IconGrid.DisposeAllChildren();

        for (var i = 0; i < _jobIcons.Count; i++)
        {
            var jobIcon = _protoManager.Index(_jobIcons[i]);

            var styleBase = StyleBase.ButtonOpenBoth;
            var mod = i % JobIconColumnCount;

            if (mod == 0)
                styleBase = StyleBase.ButtonOpenRight;
            else if (mod == JobIconColumnCount - 1)
                styleBase = StyleBase.ButtonOpenLeft;

            var jobIconButton = new Button
            {
                Access = AccessLevel.Public,
                StyleClasses = { styleBase },
                MaxSize = new Vector2(42, 28),
                Group = _jobIconButtonGroup,
                Pressed = jobIcon.ID == _currentJobIconId,
                ToolTip = jobIcon.LocalizedJobName
            };

            var jobIconTexture = new TextureRect
            {
                Texture = _spriteSystem.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            };

            _jobIconButtons.Add(jobIcon.ID, jobIconButton);

            jobIconButton.AddChild(jobIconTexture);
            jobIconButton.OnPressed += _ =>
            {
                _currentJobIconId = jobIcon.ID;
                OnJobIconChanged?.Invoke(jobIcon.ID);
            };

            IconGrid.AddChild(jobIconButton);
        }
    }

    public void ReloadVerbs()
    {
        foreach (var verb in _protoManager.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            _verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }
        _verbs.Sort((a, b) => string.Compare(a.Item1, b.Item1, StringComparison.Ordinal));
    }

    public void AddVerbs()
    {
        SpeechVerbSelector.Clear();

        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in _verbs)
        {
            AddVerb(name, id);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is { } metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);

        if (verb == _verb)
            SpeechVerbSelector.SelectId(id);
    }

    public void SetCurrentName(string name)
    {
        NameLineEdit.Text = name;
    }

    public void SetCurrentSpeechVerb(ProtoId<SpeechVerbPrototype>? speechVerbProtoId)
    {
        _verb = speechVerbProtoId;

        for (int id = 0; id < SpeechVerbSelector.ItemCount; id++)
        {
            if (Equals(speechVerbProtoId, SpeechVerbSelector.GetItemMetadata(id)))
            {
                SpeechVerbSelector.SelectId(id);
                break;
            }
        }
    }

    public void SetCurrentJobIcon(ProtoId<JobIconPrototype>? jobIconProtoId)
    {
        _currentJobIconId = jobIconProtoId;

        if (jobIconProtoId is not { } protoId)
        {
            // Setar para nulo é deselecionar o botão pressionado.
            if (_jobIconButtonGroup?.Pressed is { } pressedButton)
                pressedButton.Pressed = false;

            return;
        }

        if (!_jobIconButtons.TryGetValue(protoId, out var button))
            return;

        // ButtonGroup vai cuidar para fazer o outro botão não pressionado.
        button.Pressed = true;
    }
}
