using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Targeting.Widgets;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    //private readonly TargetingUIController _controller;

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        //_controller = UserInterfaceManager.GetUIController<TargetingUIController>();
        //TargetImage.OnPressed += OnTargetImagePressed;
    }
    /*private void OnTargetImagePressed(BaseButton.ButtonEventArgs args)
    {
        _controller.CycleTarget(this);
    }

    public void SetTargetImage(Texture texture)
    {
        TargetImage.TextureNormal = texture;
    }*/

}