using System.Linq;
using Content.Shared.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Targeting.Widgets;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    private readonly TargetingUIController _controller;
    private readonly Dictionary<TargetBodyPart, (TextureButton Button, PanelContainer Panel)> _bodyPartControls;

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<TargetingUIController>();

        _bodyPartControls = new Dictionary<TargetBodyPart, (TextureButton, PanelContainer)>
        {
            { TargetBodyPart.Head, (HeadButton, (PanelContainer)HeadButton.Children.First()) },
            { TargetBodyPart.Torso, (TorsoButton, (PanelContainer)TorsoButton.Children.First()) },
            { TargetBodyPart.LeftArm, (LeftArmButton, (PanelContainer)LeftArmButton.Children.First()) },
            { TargetBodyPart.RightArm, (RightArmButton, (PanelContainer)RightArmButton.Children.First()) },
            { TargetBodyPart.LeftLeg, (LeftLegButton, (PanelContainer)LeftLegButton.Children.First()) },
            { TargetBodyPart.RightLeg, (RightLegButton, (PanelContainer)RightLegButton.Children.First()) }
        };

        foreach (var buttonPair in _bodyPartControls)
        {
            buttonPair.Value.Button.MouseFilter = MouseFilterMode.Stop;
            buttonPair.Value.Button.OnPressed += args => SetActiveBodyPart(buttonPair.Key);
        }
    }
    private void SetActiveBodyPart(TargetBodyPart bodyPart)
    {
        _controller.CycleTarget(bodyPart);
    }

    public void SetColors(TargetBodyPart bodyPart)
    {
        foreach (var buttonPair in _bodyPartControls)
        {
            var styleBox = (StyleBoxFlat) buttonPair.Value.Panel.PanelOverride!;
            styleBox.BackgroundColor = buttonPair.Key == bodyPart ? new Color(243, 10, 12, 51) : new Color(0, 0, 0, 0);
            styleBox.BorderColor = buttonPair.Key == bodyPart ? new Color(243, 10, 12, 255) : new Color(0, 0, 0, 0);
        }
    }

    public void SetVisible(bool visible)
    {
        this.Visible = visible;
    }
}