#region

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

#endregion


namespace Content.Client.Chemistry.UI;


[GenerateTypedNameReferences]
public sealed partial class TransferAmountWindow : DefaultWindow
{
    public TransferAmountWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
