// SPDX-FileCopyrightText: 2025 BarryNorfolk <barrynorfolkman@protonmail.com>
// SPDX-FileCopyrightText: 2025 BeBright <98597725+be1bright@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 LuciferEOS <stepanteliatnik2022@gmail.com>
// SPDX-FileCopyrightText: 2025 LuciferMkshelter <154002422+LuciferEOS@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 LuciferMkshelter <stepanteliatnik2022@gmail.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Message;
using Content.Goobstation.Shared.NTR;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.NTR.UI;

[GenerateTypedNameReferences]
public sealed partial class NtrTaskHistoryEntry : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public NtrTaskHistoryEntry(NtrTaskHistoryData task)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (string.IsNullOrEmpty(task.Task))
        {
            Visible = false;
            return;
        }

        if (!_prototype.TryIndex(task.Task, out NtrTaskPrototype? taskPrototype))
        {
            Visible = false;
            return;
        }

        var items = new List<string>();
        var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        if (!prototypeManager.TryIndex(task.Task, out NtrTaskPrototype? proto))
        {//to not crash the game if something goes wrong
            Visible = false;
            return;
        }

        foreach (var entry in taskPrototype.Entries)
        {
            items.Add(Loc.GetString("ntr-bounty-console-manifest-entry",
                ("amount", entry.Amount),
                ("item", Loc.GetString(entry.Name))));
        }

        ManifestLabel.SetMarkup(Loc.GetString("bounty-console-manifest-label", ("item", string.Join(", ", items))));
        RewardLabel.SetMarkup(Loc.GetString("ntr-bounty-console-reward-label", ("reward", taskPrototype.Reward)));
        IdLabel.SetMarkup(Loc.GetString("bounty-console-id-label", ("id", task.Id)));

        TimestampLabel.SetMarkup(task.Timestamp.ToString(@"hh\:mm\:ss"));

        if (task.Result == NtrTaskHistoryData.TaskResult.Completed)
            NoticeLabel.SetMarkup(Loc.GetString("bounty-console-history-notice-completed-label"));
        else
            NoticeLabel.SetMarkup(Loc.GetString("bounty-console-history-notice-skipped-label",
                ("id", task.ActorName ?? "")));
    }
}
