- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
 
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  subGear:
  - StationEngineerPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineering
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
