using Content.Shared.CartridgeLoader.Cartridges;
using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoMessageUiFragment : BoxContainer
{
    public NanoMessageUiFragment()
    {
        RobustXamlLoader.Load(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }
    public void UpdateState(NanoMessageUiState state)

    {
        RecipientsContainer.RemoveAllChildren();

        var index = 0;
        foreach (var recipient in state.KnownRecipients)
        {
            var entry = new NanoMessageEntryRecipient(++index, recipient);
            RecipientsContainer.AddChild(entry);
        }
    }
}

