//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_post_data_t
    {
        internal cef_base_ref_counted_t _base;
        internal delegate* unmanaged<cef_post_data_t*, int> _is_read_only;
        internal delegate* unmanaged<cef_post_data_t*, int> _has_excluded_elements;
        internal delegate* unmanaged<cef_post_data_t*, UIntPtr> _get_element_count;
        internal delegate* unmanaged<cef_post_data_t*, UIntPtr*, cef_post_data_element_t**, void> _get_elements;
        internal delegate* unmanaged<cef_post_data_t*, cef_post_data_element_t*, int> _remove_element;
        internal delegate* unmanaged<cef_post_data_t*, cef_post_data_element_t*, int> _add_element;
        internal delegate* unmanaged<cef_post_data_t*, void> _remove_elements;
        
        // Create
        [DllImport(libcef.DllName, EntryPoint = "cef_post_data_create", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_post_data_t* create();
        
        // AddRef
        
        public static void add_ref(cef_post_data_t* self)
        {
            self->_base._add_ref((cef_base_ref_counted_t*)self);
        }
        
        // Release
        
        public static int release(cef_post_data_t* self)
        {
            return self->_base._release((cef_base_ref_counted_t*)self);
        }
        
        // HasOneRef
        
        public static int has_one_ref(cef_post_data_t* self)
        {
            return self->_base._has_one_ref((cef_base_ref_counted_t*)self);
        }
        
        // HasAtLeastOneRef
        
        public static int has_at_least_one_ref(cef_post_data_t* self)
        {
            return self->_base._has_at_least_one_ref((cef_base_ref_counted_t*)self);
        }
        
        // IsReadOnly
        
        public static int is_read_only(cef_post_data_t* self)
        {
            return self->_is_read_only(self);
        }
        
        // HasExcludedElements
        
        public static int has_excluded_elements(cef_post_data_t* self)
        {
            return self->_has_excluded_elements(self);
        }
        
        // GetElementCount
        
        public static UIntPtr get_element_count(cef_post_data_t* self)
        {
            return self->_get_element_count(self);
        }
        
        // GetElements
        
        public static void get_elements(cef_post_data_t* self, UIntPtr* elementsCount, cef_post_data_element_t** elements)
        {
            self->_get_elements(self, elementsCount, elements);
        }
        
        // RemoveElement
        
        public static int remove_element(cef_post_data_t* self, cef_post_data_element_t* element)
        {
            return self->_remove_element(self, element);
        }
        
        // AddElement
        
        public static int add_element(cef_post_data_t* self, cef_post_data_element_t* element)
        {
            return self->_add_element(self, element);
        }
        
        // RemoveElements
        
        public static void remove_elements(cef_post_data_t* self)
        {
            self->_remove_elements(self);
        }
        
    }
}
