//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_download_handler_t
    {
        internal cef_base_ref_counted_t _base;
        internal delegate* unmanaged<cef_download_handler_t*, cef_browser_t*, cef_string_t*, cef_string_t*, int> _can_download;
        internal delegate* unmanaged<cef_download_handler_t*, cef_browser_t*, cef_download_item_t*, cef_string_t*, cef_before_download_callback_t*, void> _on_before_download;
        internal delegate* unmanaged<cef_download_handler_t*, cef_browser_t*, cef_download_item_t*, cef_download_item_callback_t*, void> _on_download_updated;
        
        internal GCHandle _obj;
        
        [UnmanagedCallersOnly]
        public static void add_ref(cef_download_handler_t* self)
        {
            var obj = (CefDownloadHandler)self->_obj.Target;
            obj.add_ref(self);
        }
        
        [UnmanagedCallersOnly]
        public static int release(cef_download_handler_t* self)
        {
            var obj = (CefDownloadHandler)self->_obj.Target;
            return obj.release(self);
        }
        
        [UnmanagedCallersOnly]
        public static int has_one_ref(cef_download_handler_t* self)
        {
            var obj = (CefDownloadHandler)self->_obj.Target;
            return obj.has_one_ref(self);
        }
        
        [UnmanagedCallersOnly]
        public static int has_at_least_one_ref(cef_download_handler_t* self)
        {
            var obj = (CefDownloadHandler)self->_obj.Target;
            return obj.has_at_least_one_ref(self);
        }
        
        [UnmanagedCallersOnly]
        public static int can_download(cef_download_handler_t* self, cef_browser_t* browser, cef_string_t* url, cef_string_t* request_method)
        {
            var obj = (CefDownloadHandler)self->_obj.Target;
            return obj.can_download(self, browser, url, request_method);
        }
        
        [UnmanagedCallersOnly]
        public static void on_before_download(cef_download_handler_t* self, cef_browser_t* browser, cef_download_item_t* download_item, cef_string_t* suggested_name, cef_before_download_callback_t* callback)
        {
            var obj = (CefDownloadHandler)self->_obj.Target;
            obj.on_before_download(self, browser, download_item, suggested_name, callback);
        }
        
        [UnmanagedCallersOnly]
        public static void on_download_updated(cef_download_handler_t* self, cef_browser_t* browser, cef_download_item_t* download_item, cef_download_item_callback_t* callback)
        {
            var obj = (CefDownloadHandler)self->_obj.Target;
            obj.on_download_updated(self, browser, download_item, callback);
        }
        
        internal static cef_download_handler_t* Alloc(CefDownloadHandler obj)
        {
            var ptr = (cef_download_handler_t*)NativeMemory.Alloc((UIntPtr)sizeof(cef_download_handler_t));
            *ptr = default(cef_download_handler_t);
            ptr->_base._size = (UIntPtr)sizeof(cef_download_handler_t);
            ptr->_obj = GCHandle.Alloc(obj);
            ptr->_base._add_ref = (delegate* unmanaged<cef_base_ref_counted_t*, void>)(delegate* unmanaged<cef_download_handler_t*, void>)&add_ref;
            ptr->_base._release = (delegate* unmanaged<cef_base_ref_counted_t*, int>)(delegate* unmanaged<cef_download_handler_t*, int>)&release;
            ptr->_base._has_one_ref = (delegate* unmanaged<cef_base_ref_counted_t*, int>)(delegate* unmanaged<cef_download_handler_t*, int>)&has_one_ref;
            ptr->_base._has_at_least_one_ref = (delegate* unmanaged<cef_base_ref_counted_t*, int>)(delegate* unmanaged<cef_download_handler_t*, int>)&has_at_least_one_ref;
            ptr->_can_download = &can_download;
            ptr->_on_before_download = &on_before_download;
            ptr->_on_download_updated = &on_download_updated;
            return ptr;
        }
        
        internal static void Free(cef_download_handler_t* ptr)
        {
            ptr->_obj.Free();
            NativeMemory.Free((void*)ptr);
        }
        
    }
}
