using System.Linq;
using Content.Client.DeltaV.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeltaV.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class EditChatPopup : DefaultWindow
{
    private const int MaxInputLength = 16;
    private const int MaxNumberLength = 4;

    public event Action<uint, string, string?>? OnContactEdited;

    public EditChatPopup()
    {
        RobustXamlLoader.Load(this);

        // margins trolling
        ContentsContainer.Margin = new Thickness(3);

        // Button handlers
        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => EditChat();

        // Input validation
        NameInput.OnTextChanged += _ => ValidateInputs();

        NameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxInputLength)
                NameInput.Text = args.Text[..MaxInputLength];
            ValidateInputs();
        };

        JobInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxInputLength)
                JobInput.Text = args.Text[..MaxInputLength];
        };

        NumberInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxNumberLength)
                NumberInput.Text = args.Text[..MaxNumberLength];

            // Filter to digits only
            var newText = string.Concat(NumberInput.Text.Where(char.IsDigit));
            if (newText != NumberInput.Text)
                NumberInput.Text = newText;

            ValidateInputs();
        };
    }

    private void ValidateInputs()
    {
        var isValid = !string.IsNullOrWhiteSpace(NumberInput.Text) &&
            !string.IsNullOrWhiteSpace(NameInput.Text) &&
            uint.TryParse(NumberInput.Text, out _);

        CreateButton.Disabled = !isValid;
    }

    private void EditChat()
    {
        if (!uint.TryParse(NumberInput.Text, out var number))
            return;

        var name = NameInput.Text.Trim();
        var job = string.IsNullOrWhiteSpace(JobInput.Text) ? null : JobInput.Text.Trim();

        OnContactEdited?.Invoke(number, name, job);
        Close();
    }

    public void ClearInputs()
    {
        NameInput.Text = string.Empty;
        JobInput.Text = string.Empty;
        ValidateInputs();
    }

    public void SetNumberInput(string newNumber) => NumberInput.Text = newNumber;
    public void SetNameInput(string newName) => NameInput.Text = newName;
    public void SetJobInput(string newJob) => JobInput.Text = newJob;
}
