// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.Xenobiology.XenobiologyBountyConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Goobstation.Client.Xenobiology.XenobiologyBountyConsole;

[GenerateTypedNameReferences]
public sealed partial class XenobiologyBountyMenu : FancyWindow
{
    public Action<string>? OnFulfillButtonPressed;
    public Action<string>? OnSkipButtonPressed;

    private TimeSpan _untilNextRefresh;

    public XenobiologyBountyMenu()
    {
        RobustXamlLoader.Load(this);

        MasterTabContainer.SetTabTitle(0, Loc.GetString("bounty-console-tab-available-label"));
        MasterTabContainer.SetTabTitle(1, Loc.GetString("bounty-console-tab-history-label"));
    }

    public void UpdateEntries(List<XenobiologyBountyData> bounties, List<XenobiologyBountyHistoryData> history, TimeSpan untilNextSkip, TimeSpan untilNextRefresh)
    {
        _untilNextRefresh = untilNextRefresh;

        BountyEntriesContainer.Children.Clear();
        foreach (var bounty in bounties)
        {
            var entry = new XenobiologyBountyEntry(bounty, untilNextSkip);
            entry.OnFulfillButtonPressed += () => OnFulfillButtonPressed?.Invoke(bounty.Id);
            entry.OnSkipButtonPressed += () => OnSkipButtonPressed?.Invoke(bounty.Id);

            BountyEntriesContainer.AddChild(entry);
        }
        BountyEntriesContainer.AddChild(new Control
        {
            MinHeight = 10,
        });

        BountyHistoryContainer.Children.Clear();
        if (history.Count == 0)
        {
            NoHistoryLabel.Visible = true;
        }
        else
        {
            NoHistoryLabel.Visible = false;

            // Show the history in reverse, so last entry is first in the list
            for (var i = history.Count - 1; i >= 0; i--)
                BountyHistoryContainer.AddChild(new XenobiologyBountyHistoryEntry(history[i]));
        }
    }

    private void UpdateGlobalRefresh(float deltaSeconds)
    {
        _untilNextRefresh -= TimeSpan.FromSeconds(deltaSeconds);
        if (_untilNextRefresh > TimeSpan.Zero)
            GlobalRefreshTimer.SetMarkup(Loc.GetString("xenobiology-console-refresh-label", ("time", _untilNextRefresh.ToString("mm\\:ss"))));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateGlobalRefresh(args.DeltaSeconds);
    }
}
