// SPDX-FileCopyrightText: 2021 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2021 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Kevin Zheng <kevinz5000@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Info;

[GenerateTypedNameReferences]
public sealed partial class InfoSection : BoxContainer
{
    public InfoSection(string title, string text, bool markup = false)
    {
        RobustXamlLoader.Load(this);
        SetText(title, text, markup);
    }

    public void SetText(string title, string text, bool markup = false)
    {
        TitleLabel.Text = title;
        if (markup)
            Content.SetMessage(FormattedMessage.FromMarkupOrThrow(text.Trim()));
        else
            Content.SetMessage(text);
    }
}