#region

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

#endregion


namespace Content.Client.Administration.UI.Tabs;


[GenerateTypedNameReferences]
public sealed partial class RoundTab : Control { }
