- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Security
    min: 36000 # 10 hours
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
    - Blindness
    - Pacifist
    - BrittleBoneDisease
    - WheelchairBound
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
      - Felinid
  - !type:CharacterEmployerRequirement
    employers:
    - ZavodskoiInterstellar
    - PMCG
    - NanoTrasen
    - EastOrionCompany
  startingGear: PrisonGuardGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisonGuard"
  supervisors: job-supervisors-warden
  setPreference: true
  access:
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: PrisonGuardGear
  subGear:
  - PrisonGuardPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadPrisonGuard
    id: PrisonGuardPDA
    ears: ClothingHeadsetPrisonGuard #DeltaV
    belt: ClothingBeltSecurityFilled

- type: startingGear
  id: PrisonGuardPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitPrisonGuard
    head: ClothingHeadEnvirohelmPrisonGuard
    gloves: ClothingHandsGlovesEnviroglovesBlack
