- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScience
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatRnd
    id: SciencePDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook

- type: startingGear
  id: ScientistPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitScientist
    head: ClothingHeadEnvirohelmScientist
    gloves: ClothingHandsGlovesEnviroglovesWhite
