// SPDX-FileCopyrightText: 2025 Armok <155400926+ARMOKS@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 OnsenCapy <101037138+OnsenCapy@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 SaffronFennec <firefoxwolf2020@protonmail.com>
// SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
// SPDX-FileCopyrightText: 2025 TheBorzoiMustConsume <197824988+TheBorzoiMustConsume@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <linebarrelerenthusiast@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Shared.GameStates;
using Content.Shared.StatusIcon;
using Robust.Shared.Prototypes;
using Robust.Shared.Audio;
using Content.Shared._DV.CosmicCult.Prototypes;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Alert;
using Robust.Shared.Serialization;

namespace Content.Shared._DV.CosmicCult.Components;

/// <summary>
/// Added to entities to tag that they are a cosmic cultist. Holds nearly all cultist-relevant data! Removal of this component is used to call for a deconversion
/// </summary>
[RegisterComponent, NetworkedComponent]
[AutoGenerateComponentState]
public sealed partial class CosmicCultComponent : Component
{
    #region Housekeeping

    /// <summary>
    /// The status icon prototype displayed for cosmic cultists.
    /// </summary>
    [DataField]
    public ProtoId<FactionIconPrototype> StatusIcon = "CosmicCultIcon";
    #endregion

    #region Ability Data
    [DataField, AutoNetworkedField]
    public HashSet<ProtoId<InfluencePrototype>> UnlockedInfluences =
    [
        "InfluenceAberrantLapse",
        "InfluenceShuntSubjectivity",
        "InfluenceEschewMetabolism",
    ];

    [DataField, AutoNetworkedField]
    public HashSet<EntProtoId> CosmicCultActions =
    [
        "ActionCosmicSiphon",
        "ActionCosmicGlare",
    ];

    public HashSet<EntityUid?> ActionEntities = [];

    [DataField, AutoNetworkedField]
    public HashSet<ProtoId<InfluencePrototype>> OwnedInfluences = [];

    /// <summary>
    /// The duration of the doAfter for Siphon Entropy
    /// </summary>
    [DataField]
    public TimeSpan CosmicSiphonDelay = TimeSpan.FromSeconds(2.5f);

    /// <summary>
    /// The duration of the doAfter for Shunt Subjectivity
    /// </summary>
    [DataField]
    public TimeSpan CosmicBlankDelay = TimeSpan.FromSeconds(1.2f);

    /// <summary>
    /// The duration of Shunt Subjectivity's trip to the cosmic void
    /// </summary>
    [DataField]
    public TimeSpan CosmicBlankDuration = TimeSpan.FromSeconds(15);

    /// <summary>
    /// The duration of Vacuous Imposition's shield.
    /// </summary>
    [DataField]
    public TimeSpan CosmicImpositionDuration = TimeSpan.FromSeconds(5.8);

    /// <summary>
    /// The duration of Null Glare's flash/disorientation.
    /// </summary>
    [DataField]
    public TimeSpan CosmicGlareDuration = TimeSpan.FromSeconds(2.5f);

    /// <summary>
    /// The range of Null Glare.
    /// </summary>
    [DataField]
    public int CosmicGlareRange = 5;

    /// <summary>
    /// The movement speed penalty inflicted by Null Glare.
    /// </summary>
    [DataField]
    public float CosmicGlarePenalty = 0.7f;

    /// <summary>
    /// The stun duration inflicted by Null Glare.
    /// </summary>
    [DataField]
    public TimeSpan CosmicGlareStun = TimeSpan.FromSeconds(0.5);

    /// <summary>
    /// The duration of the Entropic Degen debuff inflicted by Siphon Entropy
    /// </summary
    [DataField]
    public TimeSpan CosmicEntropyDebuffDuration = TimeSpan.FromSeconds(30);

    /// <summary>
    /// The amount of Entropy generated by Siphon Entropy
    /// </summary>
    [DataField]
    public int CosmicSiphonQuantity = 1;
    #endregion

    #region Misc Data
    /// <summary>
    /// The amount of Entropy the user is allowed to spend at The Monument.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int EntropyBudget;

    /// <summary>
    /// The amount of Entropy the user is currently holding on to.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int EntropyStored;

    /// <summary>
    /// The maximum amount of Entropy the user can have at once.
    /// </summary>
    [DataField, AutoNetworkedField]
    public int EntropyStoredCap = 14;

    //Goobstation
    /// <summary>
    /// The value at which the monument heals each limb.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float ShitMedHeal = -3f;

    //Goobstation
    /// <summary>
    /// The probability that siphoning entropy while empowered will cause lights to flicker.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float FlickerProbability = 0.20f;

    //Goobstation
    /// <summary>
    /// The probability that siphoning entropy while empowered will cause lights to flicker.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float FlickerRange = 5f;

    //Goobstation
    /// <summary>
    /// The maximum amount of Entropy the user can have at once.
    /// </summary>
    //[DataField, AutoNetworkedField]
    //public int MonumentHealRange = 15; Erm...

    /// <summary>
    /// Wether or not this cultist has been empowered by a Malign Rift.
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool CosmicEmpowered;

    /// <summary>
    /// Whether or not this cultist needs to respirate.
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool Respiration = true;

    /// <summary>
    /// Goobstation Change - Shitchap: Whether or not this cultist was weak to holy before conversion.
    /// </summary>
    [DataField, AutoNetworkedField]
    public bool WasWeakToHoly;

    /// <summary>
    /// A string for storing what damage container this cultist had upon conversion.
    /// </summary>
    [DataField, AutoNetworkedField]
    public ProtoId<DamageContainerPrototype> StoredDamageContainer = "Biological";

    /// <summary>
    /// The alert for displaying the cultist's currently held Entropy.
    /// </summary>
    [DataField]
    public ProtoId<AlertPrototype> EntropyAlert = "CosmicEntropy";
    #endregion

    /// <summary>
    ///     The gamerule that this cultist is associated with
    /// </summary>
    [DataField(serverOnly: true)]
    public EntityUid CultGamerule;

    #region VFX & SFX
    [DataField]
    public EntProtoId SpawnWisp = "MobCosmicWisp";

    [DataField]
    public EntProtoId LapseVFX = "CosmicLapseAbilityVFX";

    [DataField]
    public EntProtoId BlankVFX = "CosmicBlankAbilityVFX";

    [DataField]
    public EntProtoId GlareVFX = "CosmicGlareAbilityVFX";
    [DataField]
    public EntProtoId AbsorbVFX = "CosmicGenericVFX";

    [DataField]
    public EntProtoId ImpositionVFX = "CosmicImpositionAbilityVFX";

    [DataField]
    public SoundSpecifier BlankSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_blank.ogg");

    [DataField]
    public SoundSpecifier IngressSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_ingress.ogg");

    [DataField]
    public SoundSpecifier GlareSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_glare.ogg");

    [DataField]
    public SoundSpecifier NovaCastSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_nova_cast.ogg");

    [DataField]
    public SoundSpecifier ImpositionSFX = new SoundPathSpecifier("/Audio/_DV/CosmicCult/ability_imposition.ogg");
    #endregion
}

[NetSerializable, Serializable]
public enum CultAlertVisualLayers : byte
{
    Counter,
}
