using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.GPS;

[GenerateTypedNameReferences]
public sealed partial class GpsListEntry : Button
{
    public NetEntity TrackedEntity;

    public GpsListEntry(string label,NetEntity trackedEntity, IRsiStateLike? icon, Color? iconColor)
    {
        RobustXamlLoader.Load(this);

        NameableLabel.Text = label;
        EntryIcon.Texture = icon?.Default;
        TrackedEntity = trackedEntity;

        if (iconColor != null)
            EntryIcon.Modulate = iconColor.Value;
    }
}
